version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Mapping host port 5433 to container port 5432 for PostgreSQL

  web:
    build: .
    command: bash -c "bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/chevi"
    ports:
      - "3000:3000"  # Expose Rails on port 3000
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    networks:
      - chevi_network

volumes:
  postgres_data:

networks:
  chevi_network:
    driver: bridge
